import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";



export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
              <a
                  className="bg-gradient-to-r from-orange-500 dark:text-white to-red-500 text-black px-4 py-2 border-none rounded-md ml-8 text-2xl"
                  href="/Atif_Khan_Resume_2024.pdf"
                  download="Atif_Khan_Resume_2024.pdf"
                >
                  Resume
                </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-4xl"
                />
              </li>

            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-orange-600 font-medium dark:text-orange-400 md:text-8xl">
              Atif Khan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-5xl">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 mx-auto md:text-3xl">
              Current Senior @ <span className="text-orange-600 dark:text-orange-400">Brown University </span>
               majoring in <span className="text-orange-600 dark:text-orange-400">Computer Science</span>
            </p>
            <a href="https://www.linkedin.com/in/atif-khan-9a478515b/" target="_blank" rel="noopener noreferrer" style={{ display: "inline-block", lineHeight: 0 }}>
  <div className="text-5xl flex justify-center text-gray-600 dark:text-gray-400">
    <AiFillLinkedin />
  </div>
</a>

            <div className="mx-auto bg-gradient-to-b from-orange-500 rounded-full w-80 h-80 relative overflow-hidden mt-5 md:h-96 md:w-96">
            <div className="absolute inset-0" style={{ top: "-30%", left: "5%" }}>
    <Image src={"/me2.png"} layout="fill" objectFit="cover" />
  </div>            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl py-1 text-orange-600 dark:text-orange-400">About Me</h3>
            <p className="text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200 d-flex justify-content-between">
              I am a person who loves to create. Whether it is making
              <span className="text-orange-600 dark:text-orange-400"> websites </span>
              or designing <span className="text-orange-600 dark:text-orange-400"> apps</span>,
              I love building things and gaining new skills and learning new technologies. 
              I have a deep and wide skillset in both frontend and backend.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={"/design.png"} width={100} height={100} />
         

              <h3 className="text-4xl py-4 text-orange-600 font-medium dark:text-orange-400">Design Tools I Use</h3>
              <p className="text-3xl  text-black-800 dark:text-white py-1">Figma</p>
              <p className="text-3xl  text-black-800 dark:text-white py-1">Balsamic</p>
              <p className="text-3xl text-black-800 dark:text-white py-1">Photoshop</p>
              <p className="text-3xl  text-black-800 dark:text-white py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={"/code.png"} width={100} height={100} />

              <h4 className="text-4xl py-4 text-orange-400">My Technology Skillset</h4>
              <p className="text-3xl text-black dark:text-white py-1">Python</p>
              <p className="text-3xl text-black dark:text-white py-1">Java</p>
              <p className="text-3xl text-black dark:text-white py-1">HTML/CSS</p>
              <p className="text-3xl text-black dark:text-white py-1">JavaScript</p>
              <p className="text-3xl text-black dark:text-white py-1">React</p>
              <p className="text-3xl text-black dark:text-white py-1">Git</p>
              <p className="text-3xl text-black dark:text-white py-1">GCP</p>



            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-5xl py-1 text-orange-600 dark:text-orange-400">Projects</h3>
            <p className="text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              I have done various projects ranging from
              <span className="text-orange-600 dark:text-orange-400"> designing </span>
              mockups for apps to 
              <span className="text-orange-600 dark:text-orange-400"> developing </span>
              websites. The projects themselves are diverse since these projects are in industries such
              as the legal industry to the vacation home rental industry.
            </p>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://uiux-portfolio-1w6u.vercel.app/briefcase">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/briefcase.PNG"}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://uiux-portfolio-1w6u.vercel.app/craigslist-redesign">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="cover"
                src={"/craigslist.PNG"}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://uiux-portfolio-1w6u.vercel.app/animelist">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="cover"
                src={"/myanimelist.PNG"}
              />
              </a>
              
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://uiux-portfolio-1w6u.vercel.app/vacation-rentals">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/vacation_homerents.png"}
              />
              </a>
            </div>

          </div>
        </section>
      </main>
    </div>
  );
}
